### ISSUE TITLE
25 Jan 2024 - Emerging Technologies Meeting Agenda

### ISSUE THREAD

**Issue by tenatzen** [finos/zenith#132]
## Date
20240125 - 10am EST/3pm GMT

## Untracked attendees
- Mark Hu
- Mitvin Shah
- Bruno Domingues
- Chima Ibebunjoh
- Alan Hammes
- Velvárt András
- Chaitali

## Theme
- Doctor Who

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Welcome & Announcements
   - [x] Updates on Blog
   - [x] Notices about upcoming events/deadlines
- [x] POC Program
   - [x] Status updates on existing programs
   - [x] Showcase announcements (if applicable)
- [x] Deep Dive
   - [x] Presentation on latest Primer
   - [x] Interview with external SME or industry insight
- [x] Any other Admin
   - [x] Changes to program
   - [x] Proposals for new Primer topics
   - [x] Prioritisation changes for existing publication schedule
- [x] Call to action
   - [x] POC Program
   - [x] Primers
   - [x] Brain Trust membership
- [x] AOB
- [x] Thanks & Close Out

### Zoom Details
- https://zoom.us/j/98538837792?pwd=ZHg3QVVnaCtOT0tEZSs5c0hrZTg1dz09
- **Meeting ID:** 985 3883 7792 
- **Passcode:** 152455

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by carlyrichmond** [comment]
Carly Richmond | Elastic

**Comment by sammoorhouse** [comment]
Sam Moorhouse | Turntabl

**Comment by awaiken** [comment]
Andrew Aitken - Hedera

**Comment by alvin-c-shih** [comment]
Alvin Shih / Morgan Stanley

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by tenatzen** [comment]
Keith O'Donnell | Feynic

**Comment by padraignix** [comment]
Meeting minutes:

1. **Regulation and Tech (RegTech) Discussion:**
   - Keith discussed the potential impact of regulations on different technologies.
   - Emphasized the need for a comparative study, focusing on objective comparisons rather than opinionated debates.
   - Proposed exploring RegTech projects with a more factual and matter-of-fact approach.

2. **AI Readiness Special Interest Group (SIG) in Finos:**
   - Keith introduced the larger AI project within Finos and shared a proposal for creating an AI Readiness SIG.
   - Encouraged participation and contributions to the SIG.

3. **Finance Element Project:**
   - Discussed two projects within Zenith related to finance elements.
   - Shared a link to the proposal for the AI Readiness SIG.
   - Discussed potential collaborations and contributions.

4. **Hackathon in a Box Discussion:**
   - Alvin Shih proposed a sustained, supported platform for ongoing projects, highlighting the need for impactful solutions.
   - Chima Ibebunjoh shared insights into the early stages of "Hackathon in a Box," aiming for continuous development.

5. **Spatial Computing and AI:**
   - Alvin Shih proposed exploring projects related to visualizations in VR and machine learning.
   - Suggested developing an exploratory data analysis tool for financial services.

6. **AI and VR Collaboration:**
   - Discussion on potential collaboration between AI and VR projects within Finos.
   - Consideration for interactive data visualizations and exploration.

7. **Hedera Hackathon Collaboration:**
   - Andrew Aitken discussed collaboration plans for the Hedera hackathon, focusing on web 3.0 DLT projects.
   - Mentioned ongoing work on making software open source under Apache.

8. **Autism Hackathon and Dei in Finos:**
   - Alvin Shih discussed the importance of sustained platforms for impactful projects.
   - Keith shared information on the Autism Hackathon, encouraging contributions and partnerships.
   - Mentioned the Diversity, Equity, and Inclusion SIG in Finos.

9. **Upcoming Lunar New Year Theme:**
   - Keith announced the upcoming theme for the next month, centered around Lunar New Year celebrations.
