### ISSUE TITLE
22 Feb 2024 - Emerging Technologies Meeting Agenda

### ISSUE THREAD

**Issue by tenatzen** [finos/zenith#136]
## Date
20240222 - 10AM ET / 3PM GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Welcome & Announcements
   - [x] New Brain Trust Members
   - [x] Updates on current projects
   - [x] Updates on Blog
   - [x] Notices about upcoming events/deadlines
- [x] POC Program
   - [x] Overview of existing blockers for ransom
   - [x] Status updates on existing programs
   - [x] Showcase announcements (if applicable)
- [x] Deep Dive
   - [x] Presentation on latest Primer
   - [x] Interview with external SME or industry insight
- [x] Any other Admin
   - [x] Changes to program
   - [x] Proposals for new Primer topics
   - [x] Prioritisation changes for existing publication schedule
- [x] Call to action
   - [x] POC Program
   - [x] Primers
   - [x] Brain Trust membership
- [x] AOB
- [x] Thanks & Close Out

### Zoom Details
- https://zoom.us/j/98538837792?pwd=ZHg3QVVnaCtOT0tEZSs5c0hrZTg1dz09
- **Meeting ID:** 985 3883 7792 
- **Passcode:** 152455

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by padraignix** [comment]
Patrick Downing | GitHub 👋

**Comment by RAI-INFO** [comment]
registered

**Comment by vbandi** [comment]
András Velvárt, Response / HexaIO

**Comment by PaulaPaul** [comment]
Paula Paul, @paulapaul Greyshore

**Comment by alvin-c-shih** [comment]
Alvin Shih / Morgan Stanley

**Comment by xevg** [comment]
Xev Gittler / xec.gittler@rbccm.com

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by chaitali-ladikkar** [comment]
Chaitali Ladikkar / Wellington Management

**Comment by padraignix** [comment]
Meeting minutes:

00:08:32.460 - 00:08:52.020: Peter Smulovics initiates the meeting, followed by Kendall Waters Perez presenting the antitrust policy and guidelines.
00:09:11.530 - 00:09:47.480: Waters Perez emphasizes adherence to antitrust laws and provides instructions for participation in Finos project meetings.
00:10:13.940 - 00:10:47.290: Smulovics discusses technical issues with audio and introduces QR codes for attendance and other purposes.
00:11:31.780 - 00:12:15.660: Smulovics announces upcoming events, including open-source events and the trading tech summit.
00:12:38.220 - 00:17:03.280: Smulovics updates on ongoing Proof of Concept (PoC) programs and invites participation in the real-time work processing project named Voxura.
00:17:25.920 - 00:21:19.560: Smulovics discusses blogs related to special computing and elaborates on its applications in finance, design considerations, user interactions, and collaboration.
00:21:48.640 - 00:22:29.780: Smulovics highlights the transformation of art experiences and emphasizes collaboration in special computing innovations. He offers introductions to Tech Passport and other companies.
00:22:51.810 - 00:24:59.190: Peter Smulovics introduces various hardware and software solutions for AR/VR applications. He mentions companies like Unreal XRio for lightweight AR glasses, Tech Passport for collaborative industry design, and hardware vendors like Meta, HTC, and Lenovo for enterprise headsets. He invites attendees to reach out for introductions to these companies.
00:25:00.270 - 00:26:11.630: Peter Smulovics introduces Mark Hu, who is set to demonstrate some AR applications using Unreal XRio glasses. Mark explains the architecture used for AR live streaming, contrasting it with other devices like Hololens.
00:26:11.800 - 00:32:46.770: Mark Hu elaborates on the advantages of using Unreal XRio glasses for AR applications, emphasizing their professional appearance, lightweight design, and support for live streaming without taxing device resources. He prepares to demonstrate various AR applications, including Google Gemi, OpenAI's GPT text-to-image completion, and voice analytics. Mark begins the demonstration, sharing his screen to showcase the applications in real-time.
00:33:57.770 - 00:41:00.140: Mark Hu demonstrates a flying tube indicator and a human avatar that follows his head movements. He explains the voice demo setup, where speech is captured by the avatar and analyzed using AI models for voice analytics.
00:41:00.350 - 00:45:22.680: Mark continues the demonstration by showcasing a Google Gemini avatar connected to the human avatar. He interacts with the Gemini avatar, asking it questions and receiving accurate responses based on image descriptions and tourism suggestions. Mark discusses the integration of Google GPT-4 into their platform and plans to compare online and offline modes in future demos.
00:45:24.020 - 00:52:22.909: Mark Hu discusses the standardized actions available in their platform, including interaction with various AI models such as Google and OpenAI GPT. He demonstrates interactions with the avatars, including asking for recipes and showing text-to-image outputs. Mark explains the configurable nature of their platform, allowing users to choose different AI models and input methods. He also addresses questions from the chat about gaze mechanism and choice of tools for the demo.
00:52:50.990 - 00:54:23.889: Mark concludes the presentation by showcasing hand tracking as an alternative input method, allowing users to interact using gestures instead of controllers. He demonstrates switching between hand tracking and controller input for different user preferences.
00:54:37.920 - 00:59:23.889: Mark Hu discusses the technical aspects of their demos, mentioning that all their code is built on the Mixed Reality Toolkit (MRTK) in Unity. He explains that their demos can run on various devices, including Apple Vision Pro, and showcases a dashboard for voice analytics. Mark elaborates on the use of biometrics for user identification and security measures implemented at the device level.
00:59:30.930 - 01:07:52.910: Peter Smulovics facilitates a discussion on the risks associated with spatial computing platforms. Mark and Peter discuss the similarities in risk profiles between spatial computing devices and traditional mobile devices. Mark emphasizes the importance of encryption and adherence to industry standards for privacy and security. Peter encourages attendees to engage further in discussions and register attendance. The meeting concludes with thanks from Peter and Mark.
