### ISSUE TITLE
25 Apr 2024 - Emerging Technologies Meeting Agenda

### ISSUE THREAD

**Issue by tenatzen** [finos/zenith#146]
## Date
20240425 - 10am EST | 3pm BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Welcome & Announcements
   - [ ] Updates on current projects
   - [ ] Notices about upcoming events/deadlines
- [ ] POC Program
   - [ ] Overview of existing blockers for ransom
- [ ] Call to action
   - [ ] POC Program
   - [ ] Primers
   - [ ] Brain Trust membership
- [ ] AOB
- [ ] Thanks & Close Out

### Zoom Details
- https://zoom.us/j/98538837792?pwd=ZHg3QVVnaCtOT0tEZSs5c0hrZTg1dz09
- **Meeting ID:** 985 3883 7792 
- **Passcode:** 152455

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by tenatzen** [comment]
Keith | Feynic

**Comment by awaiken** [comment]
Andrew Aitken - Hedera

**Comment by vbandi** [comment]
András Velvárt - Response / HexaIO

**Comment by DamianReeves** [comment]
Anyone manning hosting duties to let folks into the meeting? Is the link posted here correct?

**Comment by tenatzen** [comment]
Hey @DamianReeves, the call went ahead at the times listed. It only lasted 30m. Happy to bring you up to speed with what we covered

**Comment by padraignix** [comment]
Summary of Meeting Minutes
Date: April 25, 2024
Event: Special Interest Group Meeting

Main Points:
00:01:07 - 00:01:13
Keith J. O'Donnell starts the meeting and mentions that it will be recorded and shared afterward.
00:01:21 - 00:01:34
Keith presents the standard meeting notices, including the Linux Foundation Anti-Trust Policy and Phenos guidelines.
00:03:02 - 00:03:11
Keith welcomes attendees to the month's emergent technology special interest group meeting and mentions the use of QR codes throughout the presentation.
00:03:33 - 00:03:55
Keith provides a brief overview of the agenda and notes that the session might be shorter due to ongoing projects.
00:04:17 - 00:04:52
Announcements about upcoming events:
OSF London in June
OSF New York in September
All community call next week
00:06:01 - 00:07:09
Update on the Voxura project, focusing on real-time insights through voice transcription and analysis.
00:07:09 - 00:07:37
Keith explains the problems Voxura aims to solve, such as slow data entry and human error, especially in mobile and spatial computing contexts.
00:07:44 - 00:08:58
Demo of Voxura's functionality, showing how it can fill out forms and handle real-time data entry through voice commands.
00:09:09 - 00:11:04
Keith discusses the competitive landscape and the advantages of Voxura's approach, which includes intelligence and contextualization in real-time data handling.
00:11:21 - 00:13:06
Keith outlines the support needed for the Voxura project, including sponsorship, development resources, and financial services compliance.
00:13:09 - 00:13:32
Open floor for questions and comments:
Andrew Aitken from Hedera asks for an overview or summary deck to share internally.
Keith agrees to provide the necessary links and documents.
00:13:37 - 00:13:46
Velvárt András thanks Keith and adds that the focus is on extracting information from speech in real-time and acting on it.
00:13:46 - 00:16:00
Discussion on the project's development roadmap and the next steps, including client-server version and financial services compliance.
00:16:00 - 00:17:02
Keith mentions upcoming meetings with other FINOS teams to seek additional support for the Voxura project.
00:17:02 - 00:18:25
Rimma Perelmuter asks about the specifics of financial sponsorship, and Keith explains the process through the Brain Trust model.
00:18:28 - 00:20:09
Keith opens the floor for any other business or discussion on emergent technology but receives no further comments.
00:20:31 - 00:20:35
Keith concludes the meeting, encourages participation in the community call, and reminds attendees about the website redesign feedback.
00:20:38 - 00:20:42
Meeting adjourned.
