### ISSUE TITLE
26 Sept 2024 - Emerging Technologies Meeting Agenda

### ISSUE THREAD

**Issue by tenatzen** [finos/zenith#161]
## Date
2024 09 26 - 10am EST, 3PM BST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Welcome & Announcements
- [ ] POC Program
- [ ] Deep Dive - ATARC
- [ ] Any other Admin
- [ ] Call to action
- [ ] AOB
- [ ] Thanks & Close Out

### Zoom Details
- https://zoom.us/j/98538837792?pwd=ZHg3QVVnaCtOT0tEZSs5c0hrZTg1dz09
- **Meeting ID:** 985 3883 7792 
- **Passcode:** 152455

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by chaitali-ladikkar** [comment]
Chaitali Ladikkar -  Wellington Management

**Comment by padraignix** [comment]
Patrick Downing - GitHub

**Comment by padraignix** [comment]
00:15:38 - 00:15:55
Keith J. O'Donnell: Starts the meeting, explains the need to go through standard meeting notices in accordance with policy.

00:15:57 - 00:17:04
Keith J. O'Donnell: Reminds participants that project meetings are subject to the Linux Foundation Antitrust Policy, highlighting topics that must not be discussed. Encourages attendees to familiarize themselves with these guidelines and contact legal@finos.org with any questions.

00:17:17 - 00:18:05
Keith J. O'Donnell: Notes that Phenos project leads must follow specific guidelines, and mentions that meeting participants are subject to the Linux Foundation's antitrust policy and community code of conduct.

00:18:05 - 00:19:08
Keith J. O'Donnell: Discusses the importance of adhering to meeting agendas, highlights that attendees should not engage in activities prohibited under antitrust laws, and mentions that project meetings may be recorded for administrative purposes.

00:19:08 - 00:19:36
Keith J. O'Donnell: Welcomes participants to the September FINOS Zenith Public SIG meeting, provides attendance instructions through a GitHub link, and asks Kendall to share the link in the chat.

00:19:36 - 00:19:59
Keith J. O'Donnell: Introduces the agenda, which includes standard announcements, upcoming events, and a discussion with a special guest from the Advanced Technology Academic Research Center (ATARC).

00:20:05 - 00:20:45
Keith J. O'Donnell: Announces the ongoing FINOS Tech Sprint, a coding event, leading up to a main unveiling at the OSFF conference. Encourages participation through GitHub.

00:20:45 - 00:21:03
Keith J. O'Donnell: Mentions other events happening on the morning of OSFF, including an open source readiness roundtable, which is open to those who are not registered for OSFF.

00:21:05 - 00:21:14
Keith J. O'Donnell: Discusses the OS Climate Physical Risk Workshop, which will cover collaboration between FINOS and OS Climate, including developer engagement.

00:21:14 - 00:22:03
Keith J. O'Donnell: Announces OSFF, happening on September 30th and October 1st in New York City, and mentions that Peter Smolovics will be present and running a panel. Encourages registration and participation.

00:22:04 - 00:22:31
Kendall Waters Perez: Confirms that registration for OSFF is still open.

00:22:31 - 00:23:02
Keith J. O'Donnell: Shares that he will not be attending OSFF New York but will be participating in the Grace Hopper Celebration virtually, which will tackle bias in AI—a topic related to the AI readiness SIG.

00:23:07 - 00:23:19
Keith J. O'Donnell: Hands over to Jim StClair for the introduction of their special guest, Elizabeth Wyckoff from ATARC.

00:23:19 - 00:23:34
Jim StClair: Introduces Elizabeth Wyckoff, provides background on his experience in government contracting, and explains ATARC's purpose of connecting government, industry, and academia.

00:23:34 - 00:24:22
Jim StClair: Describes ATARC's focus on technology areas like quantum computing, generative AI, and emerging tech. Highlights the institutional and foundational relevance of these topics.

00:24:32 - 00:24:54
Elizabeth Wyckoff (ATARC): Introduces herself as the Associate Working Group Program Director, describing ATARC's role in uniting government, industry, and academia to address technology issues. Shares that she will discuss several working groups.

00:24:54 - 00:25:19
Elizabeth Wyckoff (ATARC): Shares the working group portfolio, focusing on the Generative AI, Global Quantum, and Zero Trust groups.

00:25:20 - 00:26:27
Elizabeth Wyckoff (ATARC): Discusses the Generative AI Working Group, which addresses government adoption of generative AI through governance, procurement, and planning. Mentions the creation of an info deck on trustworthy generative AI usage.

00:26:41 - 00:27:06
Elizabeth Wyckoff (ATARC): Describes the Global Quantum Group, led by representatives from NIST, GSA, and D-Wave. Highlights the monthly Quantum Speaker Series, featuring thought leaders in quantum technology.

00:27:13 - 00:28:03
Elizabeth Wyckoff (ATARC): Discusses the Zero Trust Working Group, which runs a demonstration lab for government-only audiences, allowing industry members to showcase solutions.

00:28:28 - 00:28:33
Keith J. O'Donnell: Thanks Elizabeth and asks Jim if he would like to add anything.

00:28:33 - 00:29:20
Jim StClair: Describes how ATARC's working groups align with government strategy and legislation, and emphasizes the collaboration opportunities with assistant secretaries, CISOs, and other officials.

00:29:54 - 00:30:18
Keith J. O'Donnell: Opens the floor for questions from the Zenith Group.

00:31:49 - 00:31:51
Aaman Rebello: Comments that what ATARC is doing is very interesting.

00:31:57 - 00:32:03
Nicky Clarke: Expresses interest in collaboration, especially regarding data policy and generative AI, and asks about potential alignment with the common domain model efforts.

00:32:24 - 00:33:03
Jim StClair: Agrees on the potential for collaboration and mentions discussions with LF AI and Data regarding open models. Suggests mechanisms for establishing agreements.

00:33:05 - 00:33:06
Jim StClair: Greets Robert Underwood.

00:33:10 - 00:33:41
Robert Underwood: Mentions an upcoming session at OSFF on FDC3 and generative AI, encouraging participants to attend.

00:34:55 - 00:35:03
Keith J. O'Donnell: Discusses potential next steps for collaboration, including inviting more ATARC representation to Zenith sessions and sharing guest speakers between groups.

00:35:17 - 00:36:25
Keith J. O'Donnell: Describes the bi-monthly session structure, including Brain Trust and public sessions, and invites ATARC to share updates during future public sessions.

00:36:34 - 00:36:46
Keith J. O'Donnell: Opens the floor for participants to share discussion topics for the Zenith community or suggest content for the next session.

00:37:20 - 00:37:32
Nicky Clarke: Requests input for a paper he's working on regarding the state of ontologies across financial services.

00:38:18 - 00:38:25
Keith J. O'Donnell: Asks how participants can reach out to Nicky, suggesting LinkedIn for contact.

00:38:25 - 00:38:46
Nicky Clarke: Offers to give an update at the next month's call and encourages participants to contact him via LinkedIn for collaboration.

00:39:08 - 00:39:46
Keith J. O'Donnell: Mentions sharing Elizabeth's links and Nicky's LinkedIn in an email to the Zenith group and advises on compliance when participating in external collaborations.

00:40:34 - 00:40:57
Keith J. O'Donnell: Announces the plan for future Zenith meetings, including the Brain Trust and public sessions, and shares potential schedule changes due to holidays.

00:41:00 - 00:41:21
Keith J. O'Donnell: Thanks everyone for attending, gives special thanks to Elizabeth and Jim for their presentation, and looks forward to continued communication.

00:41:26 - 00:41:30
Elizabeth Wyckoff (ATARC): Thanks everyone for allowing her to participate.

00:41:31 - 00:41:31
Keith J. O'Donnell: Concludes the meeting, wishing everyone well.
