### ISSUE TITLE
29 June 2023 - Emerging Technologies Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/zenith#33]
## Date
29 June 2023 - 10 am EST / 3pm BST

## Untracked attendees
- Alan Hammes - Morgan Stanley
- capimig (Miguel Capitao) - Deutsche Bank
- Junji Katto - Itaú Unibanco
- Karim Faraj - Bloomberg
- Ketki Tausalkar - Morgan Stanley
- Nigel Simpson - Point72
- Polina Levyant

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [x] Welcome & Announcements
   - [x] New Brain Trust Members
   - [x] Updates on current projects
   - [x] Updates on Blog
   - [x] Notices about upcoming events/deadlines
- [ ] POC Program
   - [ ] Overview of existing blockers for ransom
   - [x] Status updates on existing programs
   - [ ] Showcase announcements (if applicable)
- [ ] Deep Dive
   - [ ] Presentation on latest Primer
   - [ ] Interview with external SME or industry insight
- [ ] Any other Admin
   - [x] Changes to program
   - [x] Proposals for new Primer topics
   - [ ] Prioritisation changes for existing publication schedule
- [x] Call to arms
   - [x] POC Program
   - [x] Primers
   - [x] Brain Trust membership
- [x] AOB
- [x] Thanks & Close Out

### Zoom Details
- https://zoom.us/j/98538837792?pwd=ZHg3QVVnaCtOT0tEZSs5c0hrZTg1dz09
- **Meeting ID:** 985 3883 7792 
- **Passcode:** 152455

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley 🏢

**Comment by vbandi** [comment]
András Velvárt / Response

**Comment by mcleo-d** [comment]
James McLeod / FINOS

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by oscarwilson1999** [comment]
Oscar Wilson / Zngly

**Comment by marcomanzi** [comment]
Marco Manzi / Gedox

**Comment by winmorgan** [comment]
Win / FINOS

**Comment by MikeWilsonZngly** [comment]
Hello - Mike / Zngly

**Comment by alvin-c-shih** [comment]
Alvin Shih / Morgan Stanley

**Comment by ewencb** [comment]
Christopher Ewen / S&P Global

**Comment by cm-howard** [comment]
Chris Howard, EPAM Systems

**Comment by Perelmuter** [comment]
Rimma Perelmuter/FINOS

**Comment by tenatzen** [comment]
Keith O'Donnell/Feynic

**Comment by padraignix** [comment]
Meeting minutes from 6/29 SIG meeting:

0:00 - James McLeod - Quick intro and call to comment on issue 33 (https://github.com/finos/zenith/issues/33)
0:43 - Peter Smulovics - covers Antitrust and Meeting Notice slides
2:12 - Peter Smulovics - Introduction to SIG meeting and second reminder to comment on (https://github.com/finos/zenith/issues/33)
Keith O'Donnell:
2:34 -  Keith O'Donnell - Introducing "dancing Gab"
3:22 - Keith O'Donnell - Statement participant muting and reaction use to unmute
3:43 - Keith O'Donnell - Covering Agenda - Announcement, Deep Dives, POC Program, AOB, Thanks & Close out
4:15 - Keith O'Donnell - Covering the general topics that will be covered in a Zenith SIG meeting.
4:15 -  Keith O'Donnell - Announcements
		Usual schedule, speaking through the monthly periodic nature of the SIG meetings. Peter Smulovics confirms
	4:50 - Welcome & Announcements highlighting topics that will be covered
	5:17 - Overview of POC Program points that will be covered
	5:56 - Overview of the Deep Dive section of general meeting structure
	6:18 - Overview of Any Other Business topics
		6:48 - Example of prioritization change based on recent Apple Vision Pro announcement which expedited conversations about spatial computing
		7:12 - Overview of the Call to Arms section of the general meeting structure
		7:30 - Highlighting that AOB section of the general meeting structure is an open forum for anyone in the community to take the floor
7:54 - Announcements Slide 1. Talking through 7 blogs posted under https://zenith.finos.org/blog and future leverage of Znglists for curated content. 
8:47 - Announcements slide 2. Covering upcoming FDC3 and Morphir events immediately after the Zenith SIG meeting. Also touched the on the Aug 2nd Open Source London meetup, and the November 1 OSFF in NY. Shared the FINOS calendar in chat (https://www.finos.org/finos-community-calendar)
9:31 - Announcements slide 3. Keith covered the early members joining the brain trust: Morgan Stanley, S&P Global, Lloyds Banking Group, Citibank, AXA, Capital One, Linux Foundation, FINOS. Call to arms for more participation.
10:09 - Overview on brain trust member targets - Innovation Labs/OSPOs, Distinguished Engineers, SMEs, Individual Enthusiasts.
12:09 - Keith highlighting that initial technologies being targeted will be Spatial Computing and Quantum Computing.
13:15 - Keith allows participants to unmute to discuss the third tech priority.
13:28 - James McLeod - asks for clarification on the function of a primer.
13:45 - Keith explains that the primer is a fundamental understanding of the technology we want to detail out and what stage it is currently at. Additionally, they will cover ETAC landscapes. Keith provides example using 4D printing and hypothetical situations where primers could be leveraged.
16:23 - Mike Wilson raises hand and unmutes, discusses conversation with large bank around quantative AI, and asks how this non-FINOS member bank could potentially contribute.
17:15 - Keith explains that once the fundamental primers are released, it is open source through the Apache license allowing folks to contribute. Keith also highlights that Mike should bridge conversation with Rimma for potential membership conversations.
18:45 - Mike makes observation that AI/ML is a hot topic and asks how folks can help drive the prioritization.
18:59 - Keith makes a suggestion to the call for members to add a comment to issue 33 (https://github.com/finos/zenith/issues/33)
19:25 - Keith calls out Lloyds who came from their AI labs and are involved in the conversation as a brain trust member, suggesting we also prioritize AI as one of the initial technologies.
19:41 - Christopher Ewen - Comment on AI/NLP are hand-in-hand. Would be interested in exploring NLP. Keith confirms that there is crossover, however not mutually exclusive. Peter Smulovics elaborates on further overlaps.
20:29 - Rob Moffat - Question on whether the primers will link back to finance and identify use cases. Keith/Peter confirms yes.
22:05 - Rimma Perelmuter - Asks that in addition to the finance angle, what kind of USP could be added to further stand out? Additionally suggested to not only look at technology that is here today, but also very forward looking - brought up space technology and that the SIG could bring up clarity on why the finance industry should think about it now vs. 10 years.
23:37 - Keith - Clarification that primers are meant to provide a holistic picture of what is happening with the topic.
24:12 - Peter - Commenting that we are part of FINOS but also the larger Linux Foundation, and thinking about the larger open standardization efforts.
25:29 - Mimi Flynn - Brought up Regulatory Technology and its reach outside of finance, while commenting that it would be good to understand more of what is out there (call out to Morphir). Specifically that it would be good to take the rules that are written and understand where they conflict. (later in the call Win Morgan shared the link to https://github.com/finos/open-regtech-sig)
26:53 - Keith - Will add that point to the reg tech primer and call out Mimi on it.
26:59 - James - Comments on overlap with Zenith and Open Reg Tech Sig (Stephen Goldbaum). Highlights that we should safeguard against duplication of efforts.
28:28 - Peter - Highlights that while overlap exists, they are potentially complementary as looking into the future of certain other existing efforts as well.
29:42 - Keith - Clarifies that the Zenith mandate is to help explain the future of the tools that are going to be used.
30:18 - Rimma - Comments that policy and ethics of efforts links back to the Linux Foundations and the recent release around the importance of digital trust and sustainability. Rimma discussed that tying into the overall EU efforts of ethics and fair use could also be a way to get funding in the future, where bodies are prioritizing open source as an area for driving innovation.
32:04 - Keith - Agrees that this should be one of the things added to the primers. *Updates slide to include "ethics and fair use" and "security"*
32:53 - James - Comments that individuals speaking know each other and call to other participants to join in the discussion.
33:50 - James - Comments about Lloyds Banking exploring IoT. Poses a question to the general audience on whether anyone is looking at different ways to engage banking customers, especially in retail.
34:45 - Mimi - Mentions she is on the board of an IoT non-profit in NYC, but that they do not have finance related use cases.
34:57 - Keith - walks through a hypothetical scenario of a live music venue with tactile payment systems, setup through IoT.
35:46 - Marco ? - Brought up fair use and security in relation to connect with distributed ledger technology.
36:48 - Keith - Goes into the crossover with Governance, and overall landscape of DLT and impact to financial industry, tying in to the primer discussion.
38:04 - Alan Hammes - Asks why spatial computing is chosen as an area of focus.
38:09 - Keith - Comments that it is due to existing expertise within the SIG, specifically Peter Smulovics, Andras Velvart when it comes to spatial computing. Quantum computing was also highlighted for the same expertise through Patrick Downing and Keith's history running quantum tech programs.
39:25 - Andras Velvart - Asks for clarification on the brain trust formation and what a primer looks like. Comments that AI would most likely require multiple primers with different focuses.
40:19 - Keith - Explains primers will be the chalk outline talking about the core technology, and then hierarchal nesting of different parts more in depth. Keith called out Mike Wilson and using Znglists to establish this overarching list.
41:49 - Andras - Asked a question whether the Brain Trusts would be the ones determining this whole structure.
41:55 - Keith - Clarifies that the Brain Trust is setup to open the discourse with the trusted expertise, through recognized SMEs. The Brain Trust adds into the discussion, while Zenith runs the organization of how the program works, but as the community evolves Zenith will have its own set of best practices.
42:32 - Andras - Clarifies that he meant the organization of the subject (AI in this case) not the program itself.
42:43 - Keith - Discusses that as we post the initial details, Zenith will be looking for people to fork the details, add their own information, and have it reviewed and curated through the program.
43:02 - Peter - Mentions he posted the link to the London Member's meeting discussion on the Brain Trust formation (https://github.com/finos/zenith/blob/main/Governance/FINOS2023-06%20-%20Zenith%20Brain%20Trust%20Talk.pdf)
43:22 - Keith - Comments that the Zenith group will record a version of the brain trust meeting and post it on https://zenith.finos.org .
43:46 - Mike Wilson - Brings up that he dropped a link to next wave technologies (https://resources.nxwave.com/category/technologies/genesis/?technologies=genesis) as an example for Znglist structure by technology type.
44:15 - Keith - Mentions in the interest of time we will move on to the close up.
44:26 - Keith - Call to arms for technical experts to get involved in an interview format for the various technologies. Interested individuals can reach out to us individually, through the Zenith Slack (https://join.slack.com/t/finos-lf/shared_invite/zt-1xg6jbe0w-zmqifZ5KRoMTY_To7rhUGA to join the FINOS Slack, then https://finos-lf.slack.com/archives/C056Y8BPSDA to join the Zenith channel).
45:14 - Keith - Discusses how the POC program will work in the future, going through the 8 different steps. Alluding to going into more depth next session.
47:03 - Keith - Opening the call to AOB.
47:19 - James - Call outs for the August 2nd FINOS London meetup with Scott Logic hosted at Nat Logic (https://www.meetup.com/open-source-london/events/293930428/)
49:10 - James - Discussing the cadence of the SIG being monthly. Asked the call if there was an appetite for at the start to move it to biweekly while the SIG ramps up.
50:05 - Peter/Keith/Patrick Downing - all confirm we are good from the Zenith side to move to biweekly initially.
50:15 - Mike Wilson - Agrees that a move to biweekly makes sense.
50:55 - James - Comments that the goal of moving to biweekly is to fill up the Brain Trust faster and then get projects into development in FINOS labs.
51:08 - Keith - confirms Zenith will work with FINOS team to schedule the biweekly addition to existing monthly meeting.
51:43 - Alan Hammes - Asking whether minutes will be sent out.
51:48 - Keith - Clarifies with James on standard process for SIG meetings.
51:51 - James - Confirms that adding minutes to the github issue allows to keep everything in a single location.
52:03 - Alan Hammes - Comments that not everyone has access to Zoom chat and whether someone could email the links discussed and shared.
52:11 - Keith - confirms that links will be included in minutes and on the issue.
52:30 - Keith - Call out to https://zenith.finos.org as a central location of information.
52:57 - James - Mentions that if Alan sends a mail to zenith+subscribe@lists.finos.org that the minutes would be sent out to the list afterwards.
53:40 - Keith - adds zenith+subscribe@lists.finos.org to the slide deck to highlight and adds in that sending a blank email to the list will allow individuals to get on the list.
54:16 - Keith - Comments that it is 5 mins to the top of the hour, wraps up conversation, thanks the participants, and closes out the call.

**Comment by vbandi** [comment]
@padraignix I hope this summary was generated by AI :)
